### ISSUE TITLE
.Net Core/Standard Packages

### ISSUE THREAD

**Issue by wahmedswl** [fsprojects/Paket#2431]
### Description

It seems like Paket is now pulling up .net core/standard packages but Project is only Targetting .Net framework, nothing special. It was only used to resolve .net packages before

### Repro steps

packet.dependencies

```
source https://api.nuget.org/v3/index.json
framework: >= net40
nuget Cake
nuget GitInfo

nuget SharpRaven == 2.1.0

nuget xunit
nuget xunit.abstractions
nuget xunit.assert
nuget xunit.core
nuget xunit.extensibility.core
nuget xunit.extensibility.execution
nuget xunit.runner.console
```

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior
Paket version 4.8.8
```
Resolving packages for group Main:
 - SharpRaven 2.1.0
 - Cake 0.20
 - GitInfo 1.1.62
 - xunit 2.2
 - xunit.abstractions 2.0.1
 - xunit.assert 2.2
 - xunit.core 2.2
 - xunit.extensibility.core 2.2
 - xunit.extensibility.execution 2.2
 - xunit.runner.console 2.2
 - Newtonsoft.Json 10.0.2
```

### Actual behavior
Paket version 5.0.0
```
Resolving packages for group Main:
 - SharpRaven 2.1.0
 - Cake 0.20
 - GitInfo 1.1.65
 - xunit 2.2
 - xunit.abstractions 2.0.1
 - xunit.assert 2.2
 - xunit.core 2.2
 - xunit.extensibility.core 2.2
 - xunit.extensibility.execution 2.2
 - xunit.runner.console 2.2
 - Newtonsoft.Json 10.0.2
 - NETStandard.Library 1.6.1
 - System.Collections 4.3
 - System.Collections.Concurrent 4.3
 - System.Diagnostics.Debug 4.3
 - System.Diagnostics.Tools 4.3
 - System.Diagnostics.Tracing 4.3
 - System.Globalization 4.3
 - System.IO 4.3
 - System.IO.Compression 4.3
 - System.Linq 4.3
 - System.Linq.Expressions 4.3
 - System.Net.Http 4.3.2
 - System.Net.Primitives 4.3
 - System.ObjectModel 4.3
 - System.Reflection 4.3
 - System.Reflection.Extensions 4.3
 - System.Reflection.Primitives 4.3
 - System.Resources.ResourceManager 4.3
 - System.Runtime 4.3
 - System.Runtime.Extensions 4.3
 - System.Runtime.InteropServices 4.3
 - System.Runtime.InteropServices.RuntimeInformation 4.3
 - System.Runtime.Numerics 4.3
 - System.Text.Encoding 4.3
 - System.Text.Encoding.Extensions 4.3
 - System.Text.RegularExpressions 4.3
 - System.Threading 4.3
 - System.Threading.Tasks 4.3
 - System.Threading.Timer 4.3
 - System.Xml.ReaderWriter 4.3
 - System.Xml.XDocument 4.3
 - Microsoft.NETCore.Platforms 1.1
Locked version resolution written to E:\Development\Production-WS\Infrastructure\paket.lock
Could not detect any platforms from 'xamarin.tvos1.0'
Could not detect any platforms from 'xamarin.tvos1.0'
Could not detect any platforms from 'xamarin.tvos1.0'
Could not detect any platforms from 'xamarin.tvos1.0'
Could not detect any platforms from 'xamarin.watchos1.0'
Could not detect any platforms from 'xamarin.watchos1.0'
Could not detect any platforms from 'xamarin.watchos1.0'
Could not detect any platforms from 'xamarin.watchos1.0'
Could not detect any platforms from 'xamarintvos10'
Could not detect any platforms from 'xamarinwatchos10'
Could not detect any platforms from 'xamarintvos10'
Could not detect any platforms from 'xamarintvos10'
Could not detect any platforms from 'xamarintvos10'
Could not detect any platforms from 'xamarintvos10'
Could not detect any platforms from 'xamarintvos10'
Performance:
 - Resolver: 19 seconds (1 runs)
    - Runtime: 310 milliseconds
    - Blocked (retrieving package details): 14 seconds (36 times)
    - Blocked (retrieving package versions): 4 seconds (13 times)
    - Not Blocked (retrieving package details): 7 times
    - Not Blocked (retrieving package versions): 29 times
 - Disk IO: 421 milliseconds
 - Average Download Time: 10 milliseconds
 - Number of downloads: 1
 - Average Request Time: 2 seconds
 - Number of Requests: 52
 - Runtime: 22 seconds
```

paket.lock file structure also been changed, it used to be like
```
FRAMEWORK: >= NET40
NUGET
  remote: https://api.nuget.org/v3/index.json
    Cake (0.20)
    GitInfo (1.1.62)
    Newtonsoft.Json (10.0.2)
    SharpRaven (2.1)
      Newtonsoft.Json (>= 6.0.6)
    xunit (2.2)
      xunit.assert (2.2)
      xunit.core (2.2)
    xunit.abstractions (2.0.1)
    xunit.assert (2.2)
    xunit.core (2.2)
      xunit.extensibility.core (2.2)
      xunit.extensibility.execution (2.2)
    xunit.extensibility.core (2.2)
      xunit.abstractions (>= 2.0.1) - framework: >= net452
    xunit.extensibility.execution (2.2)
      xunit.extensibility.core (2.2) - framework: >= net452
    xunit.runner.console (2.2)
```
but its now looks like this
```
RESTRICTION: >= net40
NUGET
  remote: https://api.nuget.org/v3/index.json
    Cake (0.20)
    GitInfo (1.1.65)
    Microsoft.NETCore.Platforms (1.1) - restriction: && (>= net40) (< net452) (>= netstandard11)
    NETStandard.Library (1.6.1) - restriction: && (>= net40) (< net452) (>= netstandard11)
      Microsoft.NETCore.Platforms (>= 1.1) - restriction: && (>= net40) (>= netstandard10)
      System.Collections (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Collections.Concurrent (>= 4.3) - restriction: && (>= net40) (>= netstandard11)
      System.Diagnostics.Debug (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Diagnostics.Tools (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Diagnostics.Tracing (>= 4.3) - restriction: && (>= net40) (>= netstandard11)
      System.Globalization (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.IO (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.IO.Compression (>= 4.3) - restriction: && (>= net40) (>= netstandard11)
      System.Linq (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Linq.Expressions (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Net.Http (>= 4.3) - restriction: && (>= net40) (>= netstandard11)
      System.Net.Primitives (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.ObjectModel (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Reflection (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Reflection.Extensions (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Reflection.Primitives (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Resources.ResourceManager (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Runtime (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Runtime.Extensions (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Runtime.InteropServices (>= 4.3) - restriction: && (>= net40) (>= netstandard11)
      System.Runtime.InteropServices.RuntimeInformation (>= 4.3) - restriction: && (>= net40) (>= netstandard11)
      System.Runtime.Numerics (>= 4.3) - restriction: && (>= net40) (>= netstandard11)
      System.Text.Encoding (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Text.Encoding.Extensions (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Text.RegularExpressions (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Threading (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Threading.Tasks (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Threading.Timer (>= 4.3) - restriction: && (>= net40) (>= netstandard12)
      System.Xml.ReaderWriter (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
      System.Xml.XDocument (>= 4.3) - restriction: && (>= net40) (>= netstandard10)
    Newtonsoft.Json (10.0.2)
    SharpRaven (2.1)
      Newtonsoft.Json (>= 6.0.6)
    System.Collections (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Collections.Concurrent (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Diagnostics.Debug (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Diagnostics.Tools (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Diagnostics.Tracing (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Globalization (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.IO (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.IO.Compression (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Linq (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Linq.Expressions (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Net.Http (4.3.2) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Net.Primitives (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.ObjectModel (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Reflection (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Reflection.Extensions (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Reflection.Primitives (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Resources.ResourceManager (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Runtime (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Runtime.Extensions (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Runtime.InteropServices (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Runtime.InteropServices.RuntimeInformation (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Runtime.Numerics (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Text.Encoding (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Text.Encoding.Extensions (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Text.RegularExpressions (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Threading (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Threading.Tasks (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Threading.Timer (4.3) - restriction: && (>= net40) (< net452) (>= netstandard12)
    System.Xml.ReaderWriter (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    System.Xml.XDocument (4.3) - restriction: && (>= net40) (< net452) (>= netstandard11)
    xunit (2.2)
      xunit.assert (2.2)
      xunit.core (2.2)
    xunit.abstractions (2.0.1)
    xunit.assert (2.2)
      NETStandard.Library (>= 1.6) - restriction: && (>= net40) (< net452) (>= netstandard11)
    xunit.core (2.2)
      xunit.extensibility.core (2.2)
      xunit.extensibility.execution (2.2)
    xunit.extensibility.core (2.2)
      NETStandard.Library (>= 1.6) - restriction: && (>= net40) (< net452) (>= netstandard11)
      xunit.abstractions (>= 2.0.1) - restriction: && (>= net40) (>= netstandard11)
    xunit.extensibility.execution (2.2)
      NETStandard.Library (>= 1.6) - restriction: && (>= net40) (< net452) (>= netstandard11)
      xunit.extensibility.core (2.2) - restriction: && (>= net40) (>= netstandard11)
    xunit.runner.console (2.2)
```
