### ISSUE TITLE
Stack overflow when install Akka.Cluster.Sharding

### ISSUE THREAD

**Issue by mastoj** [fsprojects/Paket#2790]
Tried to install `Akka.Cluster.Sharding 1.3.1-beta52` in a project where I had the following `paket.dependencies`:

```
source https://www.nuget.org/api/v2
nuget Akka 1.2.3
nuget Akka.FSharp 1.2.3
nuget Suave 2.2.1
```
It blows up on one of the dependencies and I have no clue what is going on. 

Paket version: 5.92.100
OS: OSX
Mono version: 4.8.1
dotnet version: 2.0.0

Output and stack trace:
```
Paket version 5.92.100
Adding Akka.Cluster.Sharding 1.3.1-beta52 to /Users/tomasjansson/tmp/ActorPipeline/paket.dependencies into group Main
Resolving packages for group Main:
 - Suave 2.2.1
 - Akka.Cluster.Sharding 1.3.1-beta52
 - Akka 1.2.3
 - Akka.FSharp 1.2.3
 - Newtonsoft.Json 10.0.3
 - System.ValueTuple 4.4
 - System.Globalization.Extensions 4.3
 - System.Security.Cryptography.Primitives 4.3
 - FSharp.Core 4.2.3
 - System.Data.Common 4.3
 - System.Diagnostics.Process 4.3
 - System.Runtime.Serialization.Json 4.3
 - System.Security.Claims 4.3
 - System.Net.Security 4.3.1
 - FsPickler 3.3
 - FSPowerPack.Core.Community 3.0
 - FSPowerPack.Linq.Community 3.0
 - NETStandard.Library 2.0
 - System.Collections.Immutable 1.4
 - Akka.Cluster.Tools 1.3.1
 - Akka.Persistence 1.3.1
 - System.Collections.Immutable 1.3.1
 - NETStandard.Library 1.6.1
 - FsPickler 4.3.0
     FsPickler 4.3.0 was unlisted
 - FsPickler 4.0.0
 - FsPickler 3.4.0
 - FsPickler 3.2.0
 - System.Net.Security 4.3.2
 - System.Net.Security 4.3.0
 - System.Net.Security 4.0.2
Stack overflow in unmanaged: IP: 0x3975ac, fault addr: 0xbf7a0fac
Stack overflow in unmanaged: IP: 0x15399c, fault addr: 0xbf79f37c
Stack overflow in unmanaged: IP: 0x128ab0, fault addr: 0xbf79fefc
Stack overflow in unmanaged: IP: 0x3974d5, fault addr: 0xbf79effc
Stack overflow in unmanaged: IP: 0x371bc5, fault addr: 0xbf79dffc
Stack overflow in unmanaged: IP: 0x3975ac, fault addr: 0xbf79cf6c
Stack overflow in unmanaged: IP: 0x3975ac, fault addr: 0xbf79bf7c
Stack overflow in unmanaged: IP: 0x3995e7, fault addr: 0xbf79affc
Stack overflow in unmanaged: IP: 0x3975ac, fault addr: 0xbf799fec
Stack overflow: IP: 0x3975ac, fault addr: 0xbf797f5c
Stacktrace:
  at <unknown> <0xffffffff>
  at (wrapper alloc) object.AllocSmall (intptr,intptr) <0x000a3>
  <...>
  at System.Exception.Init () [0x00020] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at System.Exception..ctor (string) [0x00006] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at System.SystemException..ctor (string) [0x00000] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at System.OutOfMemoryException..ctor () [0x00007] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x0004d] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at <unknown> <0xffffffff>
  at System.Threading.CancellationTokenSource.NotifyCancellation (bool) [0x00074] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at System.Threading.CancellationTokenSource.Cancel (bool) [0x00006] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
  at Paket.PackageResolver.Resolve (Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageVersionsParameters, Microsoft.FSharp.Control.FSharpAsync`1<System.Collections.Generic.IEnumerable`1<System.Tuple`2<Paket.SemVerInfo, Microsoft.FSharp.Collections.FSharpList`1<Paket.PackageSources/PackageSource>>>>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.ResolverStrategy, Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageVersionsParameters, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<Paket.SemVerInfo, Microsoft.FSharp.Collections.FSharpList`1<Paket.PackageSources/PackageSource>>>>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageDetailsParameters, Microsoft.FSharp.Control.FSharpAsync`1<Paket.PackageResolver/PackageDetails>>,Paket.Domain/GroupName,Microsoft.FSharp.Core.FSharpOption`1<Paket.ResolverStrategy>,Microsoft.FSharp.Core.FSharpOption`1<Paket.ResolverStrategy>,Paket.Requirements/FrameworkRestrictions,Microsoft.FSharp.Collections.FSharpSet`1<Paket.Requirements/PackageRequirement>,Paket.PackageResolver/UpdateMode) [0x0049d] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at <StartupCode$Paket-Core>.$DependenciesFile/resolveGroup@212-1<b_REF>.Invoke (Paket.Domain/GroupName,b_REF) [0x000b8] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt<a_REF, b_REF, c_REF> (Microsoft.FSharp.Core.OptimizedClosures/FSharpFunc`3<a_REF, b_REF, c_REF>,Microsoft.FSharp.Collections.MapTree`2<a_REF, b_REF>) [0x0002a] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Microsoft.FSharp.Collections.FSharpMap`2<TKey_REF, TValue_REF>.Map<b_REF> (Microsoft.FSharp.Core.FSharpFunc`2<TKey_REF, Microsoft.FSharp.Core.FSharpFunc`2<TValue_REF, b_REF>>) [0x00014] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Microsoft.FSharp.Collections.MapModule.Map<TKey_REF, T_REF, TResult_REF> (Microsoft.FSharp.Core.FSharpFunc`2<TKey_REF, Microsoft.FSharp.Core.FSharpFunc`2<T_REF, TResult_REF>>,Microsoft.FSharp.Collections.FSharpMap`2<TKey_REF, T_REF>) [0x00001] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.DependenciesFile.Resolve<a_REF> (bool,Microsoft.FSharp.Core.FSharpFunc`2<Paket.ModuleResolver/Origin, Microsoft.FSharp.Core.FSharpFunc`2<string, Microsoft.FSharp.Core.FSharpFunc`2<string, Microsoft.FSharp.Core.FSharpFunc`2<Paket.ModuleResolver/VersionRestriction, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.FSharpOption`1<string>, string>>>>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageVersionsParameters, Microsoft.FSharp.Control.FSharpAsync`1<System.Collections.Generic.IEnumerable`1<System.Tuple`2<Paket.SemVerInfo, Microsoft.FSharp.Collections.FSharpList`1<Paket.PackageSources/PackageSource>>>>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.ResolverStrategy, Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageVersionsParameters, Microsoft.FSharp.Collections.FSharpList`1<System.Tuple`2<Paket.SemVerInfo, Microsoft.FSharp.Collections.FSharpList`1<Paket.PackageSources/PackageSource>>>>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageDetailsParameters, Microsoft.FSharp.Control.FSharpAsync`1<Paket.PackageResolver/PackageDetails>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.Domain/GroupName, Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/ResolvedPackage, Microsoft.FSharp.Core.FSharpOption`1<Paket.RuntimeGraph>>>,Microsoft.FSharp.Collections.FSharpMap`2<Paket.Domain/GroupName, a_REF>,Paket.PackageResolver/UpdateMode) [0x00013] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.UpdateProcess.selectiveUpdate (bool,Microsoft.FSharp.Core.FSharpFunc`2<Paket.ModuleResolver/Origin, Microsoft.FSharp.Core.FSharpFunc`2<string, Microsoft.FSharp.Core.FSharpFunc`2<string, Microsoft.FSharp.Core.FSharpFunc`2<Paket.ModuleResolver/VersionRestriction, Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.FSharpOption`1<string>, string>>>>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageVersionsParameters, Microsoft.FSharp.Control.FSharpAsync`1<System.Collections.Generic.IEnumerable`1<System.Tuple`2<Paket.SemVerInfo, Microsoft.FSharp.Collections.FSharpList`1<Paket.PackageSources/PackageSource>>>>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/GetPackageDetailsParameters, Microsoft.FSharp.Control.FSharpAsync`1<Paket.PackageResolver/PackageDetails>>,Microsoft.FSharp.Core.FSharpFunc`2<Paket.Domain/GroupName, Microsoft.FSharp.Core.FSharpFunc`2<Paket.PackageResolver/ResolvedPackage, Microsoft.FSharp.Core.FSharpOption`1<Paket.RuntimeGraph>>>,Paket.LockFile,Paket.DependenciesFile,Paket.PackageResolver/UpdateMode,Paket.SemVerUpdateMode) [0x0020d] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.UpdateProcess.SelectiveUpdate (Paket.DependenciesFile,Microsoft.FSharp.Core.FSharpOption`1<string>,Paket.PackageResolver/UpdateMode,Paket.SemVerUpdateMode,bool) [0x000e6] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.AddProcess.add (bool,Microsoft.FSharp.Core.FSharpFunc`2<System.Collections.Generic.IEnumerable`1<Paket.ProjectFile>, Microsoft.FSharp.Core.FSharpFunc`2<Paket.Domain/GroupName, Microsoft.FSharp.Core.FSharpFunc`2<Paket.Domain/PackageName, Microsoft.FSharp.Core.Unit>>>,string,Paket.Domain/GroupName,Paket.Domain/PackageName,string,Paket.InstallerOptions,bool) [0x0006a] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at <StartupCode$Paket-Core>.$PublicAPI/Add@143-17.Invoke (Microsoft.FSharp.Core.Unit) [0x0005d] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Utils.RunInLockedAccessMode<a_REF> (string,Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit, a_REF>) [0x0005c] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Dependencies.Add (Microsoft.FSharp.Core.FSharpOption`1<string>,string,string,bool,bool,bool,bool,bool,bool,Paket.SemVerUpdateMode,bool) [0x00025] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program.add (Argu.ParseResults`1<Paket.Commands/AddArgs>) [0x00c2b] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program/handleCommand@723.Invoke (Argu.ParseResults`1<Paket.Commands/AddArgs>) [0x00001] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program.processWithValidationEx$cont@37<a_REF> (bool,Microsoft.FSharp.Core.FSharpFunc`2<a_REF, Microsoft.FSharp.Core.Unit>,a_REF,Microsoft.FSharp.Core.Unit) [0x00002] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program.processWithValidationEx<a_REF> (Microsoft.FSharp.Core.FSharpFunc`2<a_REF, Microsoft.FSharp.Core.Unit>,bool,Microsoft.FSharp.Core.FSharpFunc`2<a_REF, bool>,Microsoft.FSharp.Core.FSharpFunc`2<a_REF, Microsoft.FSharp.Core.Unit>,a_REF) [0x00060] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program.processWithValidation<T_REF> (bool,Microsoft.FSharp.Core.FSharpFunc`2<Argu.ParseResults`1<T_REF>, bool>,Microsoft.FSharp.Core.FSharpFunc`2<Argu.ParseResults`1<T_REF>, Microsoft.FSharp.Core.Unit>,Argu.ParseResults`1<T_REF>) [0x00006] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program.processCommand<a_REF> (bool,Microsoft.FSharp.Core.FSharpFunc`2<Argu.ParseResults`1<a_REF>, Microsoft.FSharp.Core.Unit>,Argu.ParseResults`1<a_REF>) [0x00007] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program.handleCommand (bool,Paket.Commands/Command) [0x00091] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at Paket.Program.main () [0x003c4] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at <StartupCode$paket>.$Paket.Program.main@ () [0x0000b] in <3a014f85f3b44cb28313c2ca399767c1>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0004c] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
```

**Comment by forki** [comment]
I can't repro locally on windows. /cc @nosami @matthid mono bug?
Let's see CI: https://github.com/fsprojects/Paket/pull/2793

**Comment by mastoj** [comment]
Would this possible happen if the package I’m installing doesn’t support dotnet core?

**Comment by forki** [comment]
no we don't call into these packages. I dunno what the error is

**Comment by nosami** [comment]
Looks like a and old mono bug to me that was fixed some time ago. Try a newer version.

**Comment by mastoj** [comment]
Got it. Will try today or later this week and report back.

**Comment by mastoj** [comment]
Updated to mono 5.2.0.224 but still the same problem.

**Comment by nosami** [comment]
Working ok here on newer Mono

```
18:14 $ paket install
Paket version 5.100.2
Resolving packages for group Main:
 - Suave is pinned to 2.2.1
 - Akka is pinned to 1.2.3
 - Akka.FSharp is pinned to 1.2.3
 - Newtonsoft.Json 10.0.3
 - System.ValueTuple 4.4.0
 - System.Globalization.Extensions 4.3.0
 - System.Security.Cryptography.Primitives 4.3.0
 - FSharp.Core 4.2.3
 - System.Data.Common 4.3.0
 - System.Diagnostics.Process 4.3.0
 - System.Runtime.Serialization.Json 4.3.0
 - System.Security.Claims 4.3.0
 - System.Net.Security 4.3.2
 - FsPickler 4.3.0
     FsPickler 4.3.0 was unlisted
 - FsPickler 4.0.0
 - FSPowerPack.Core.Community 3.0.0.0
 - FSPowerPack.Linq.Community 3.0.0.0
 - NETStandard.Library 2.0.0
 - System.Collections.Immutable 1.4.0
 - System.Net.Http 4.3.3
 - runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - Microsoft.Win32.Primitives 4.3.0
 - System.AppContext 4.3.0
 - System.Collections 4.3.0
 - System.Collections.Concurrent 4.3.0
 - System.Console 4.3.0
 - System.Diagnostics.Debug 4.3.0
 - System.Diagnostics.Tools 4.3.0
 - System.Diagnostics.Tracing 4.3.0
 - System.Globalization 4.3.0
 - System.Globalization.Calendars 4.3.0
 - System.IO 4.3.0
 - System.IO.Compression 4.3.0
 - System.IO.Compression.ZipFile 4.3.0
 - System.IO.FileSystem 4.3.0
 - System.IO.FileSystem.Primitives 4.3.0
 - System.Linq 4.3.0
 - System.Linq.Expressions 4.3.0
 - System.Net.Primitives 4.3.0
 - System.Net.Sockets 4.3.0
 - System.ObjectModel 4.3.0
 - System.Reflection 4.3.0
 - System.Reflection.Extensions 4.3.0
 - System.Reflection.Primitives 4.3.0
 - System.Resources.ResourceManager 4.3.0
 - System.Runtime 4.3.0
 - System.Runtime.Extensions 4.3.0
 - System.Runtime.Handles 4.3.0
 - System.Runtime.InteropServices 4.3.0
 - System.Runtime.InteropServices.RuntimeInformation 4.3.0
 - System.Runtime.Numerics 4.3.0
 - System.Security.Cryptography.Algorithms 4.3.0
 - System.Security.Cryptography.Encoding 4.3.0
 - System.Security.Cryptography.X509Certificates 4.3.1
 - System.Text.Encoding 4.3.0
 - System.Text.Encoding.Extensions 4.3.0
 - System.Text.RegularExpressions 4.3.0
 - System.Threading 4.3.0
 - System.Threading.Tasks 4.3.0
 - System.Threading.Timer 4.3.0
 - System.Xml.ReaderWriter 4.3.0
 - System.Xml.XDocument 4.3.0
 - Microsoft.CSharp 4.4.0
 - System.ComponentModel.TypeConverter 4.3.0
 - System.Runtime.Serialization.Formatters 4.3.0
 - System.Runtime.Serialization.Primitives 4.3.0
 - System.Xml.XmlDocument 4.3.0
 - Microsoft.Win32.Registry 4.4.0
 - runtime.native.System 4.3.0
 - System.Threading.Thread 4.3.0
 - System.Threading.ThreadPool 4.3.0
 - runtime.native.System.Net.Security 4.3.0
 - System.Security.Cryptography.OpenSsl 4.4.0
 - System.Security.Principal 4.3.0
 - System.Private.DataContractSerialization 4.3.0
 - System.Net.Requests 4.3.0
 - System.Linq.Queryable 4.3.0
 - System.Threading.Tasks.Parallel 4.3.0
 - Microsoft.NETCore.Platforms 2.0.0
 - System.Security.AccessControl 4.4.0
 - System.Security.Principal.Windows 4.4.0
 - runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
 - System.Dynamic.Runtime 4.3.0
 - System.Reflection.TypeExtensions 4.4.0
 - System.Collections.NonGeneric 4.3.0
 - System.Collections.Specialized 4.3.0
 - System.ComponentModel 4.3.0
 - System.ComponentModel.Primitives 4.3.0
 - runtime.native.System.IO.Compression 4.3.1
 - System.Buffers 4.4.0
 - System.Reflection.Emit 4.3.0
 - System.Reflection.Emit.ILGeneration 4.3.0
 - System.Reflection.Emit.Lightweight 4.3.0
 - runtime.native.System.Net.Http 4.3.0
 - System.Diagnostics.DiagnosticSource 4.4.1
 - System.Net.WebHeaderCollection 4.3.0
 - System.Xml.XmlSerializer 4.3.0
 - runtime.native.System.Security.Cryptography.Apple 4.3.1
 - System.Security.Cryptography.Cng 4.4.0
 - System.Security.Cryptography.Csp 4.3.0
 - System.Threading.Tasks.Extensions 4.4.0
 - Microsoft.NETCore.Targets 2.0.0
 - runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.1
Locked version resolution written to /Users/jason/src/fsharpbugs/paket2790/paket.lock
Installing into projects:
 - Creating model and downloading packages.
Downloading Akka.FSharp 1.2.3
Downloading runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading FsPickler 4.0.0
Downloading FSPowerPack.Linq.Community 3.0.0.0
Downloading runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading FSPowerPack.Core.Community 3.0.0.0
Downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.1
Downloading runtime.native.System.Security.Cryptography.Apple 4.3.1
Downloading runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading Suave 2.2.1
Downloading runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading runtime.native.System.IO.Compression 4.3.1
Downloading Microsoft.NETCore.Targets 2.0.0
Downloading Akka 1.2.3
Downloading runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2
Downloading System.Data.Common 4.3.0
Downloading System.Net.Http 4.3.3
Downloading System.Net.Security 4.3.2
Downloading System.Private.DataContractSerialization 4.3.0
Downloading System.Reflection.TypeExtensions 4.4.0
Downloading System.Runtime.Serialization.Json 4.3.0
Downloading System.Security.Cryptography.Cng 4.4.0
Downloading System.Security.Cryptography.OpenSsl 4.4.0
Downloading System.Security.Cryptography.X509Certificates 4.3.1
Downloading System.Xml.XmlSerializer 4.3.0
Could not detect any platforms from 'sl3-wp' in '/Users/jason/src/fsharpbugs/paket2790/packages/FSPowerPack.Core.Community/Lib/sl3-wp/FSharp.PowerPack.Compatibility.dll', please tell the package authors
Performance:
 - Resolver: 1 minute, 52 seconds (1 runs)
    - Runtime: 1 minute, 20 seconds
    - Blocked (retrieving package details): 28 seconds (31 times)
    - Blocked (retrieving package versions): 3 seconds (5 times)
    - Not Blocked (retrieving package details): 81 times
    - Not Blocked (retrieving package versions): 106 times
 - Disk IO: 44 seconds
 - Average Download Time: 12 seconds
 - Number of downloads: 31
 - Average Request Time: 831 milliseconds
 - Number of Requests: 396
 - Runtime: 2 minutes, 18 seconds
Paket omitted 7 warnings similar to the ones above. You can see them in verbose mode.
✔ ~/src/fsharpbugs/paket2790 [master L|…4334]
18:16 $ mono --version
Mono JIT compiler version 5.4.0.130 (2017-06/e9d3a69 Tue Jul 25 05:56:19 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          yes(3.6.0svn-mono-master/8b1520c)
        GC:            sgen (concurrent by default)
✔ ~/src/fsharpbugs/paket2790 [master L|…4334]
18:16 $ cat paket.dependencies
source https://www.nuget.org/api/v2
nuget Akka 1.2.3
nuget Akka.FSharp 1.2.3
nuget Suave 2.2.1
```

Let me downgrade and see what happens.
