### ISSUE TITLE
Invalid CIL/Null reference exception on call to paket.exe

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#3369]
### Description

For some reason our CI for Hopac started failing with:
>   System.NullReferenceException: Object reference not set to an instance of an object
from https://travis-ci.org/Hopac/Hopac/jobs/430883446#L1829

...and...

> /home/travis/build/Hopac/Hopac/.paket/Paket.Restore.targets(81,5): error MSB3073: The command "mono --runtime=v4.0.30319 "/home/travis/build/Hopac/Hopac/.paket/paket.exe" restore" exited with code 1. [/home/travis/build/Hopac/Hopac/Benchmarks/ThreadRing/ThreadRing.fsproj]

For code https://github.com/Hopac/Hopac/commits/master

### Repro steps

Please provide the steps required to reproduce the problem

```
language: csharp
sudo: false  # use the new container-based Travis infrastructure
install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.7.1/
env: CONFIGS=Release
os: linux
dotnet: 2.1.402

matrix:
  include:
    - mono: latest
  exclude:
    - env: CONFIGS=Release

script: ./run tests
```

for the above code base.

### Expected behavior

Not to crash.

### Actual behavior

Internal error somewhere in mono 5.14.

### Known workarounds

Since we don't have any caches declared in the travis file, I don't see why this started happening and is happening on every run now. I can run it all locally just fine with mono 5.14.
